### PR TITLE
Move the braille code registry candidates to an editor's note

### PR DESCRIPTION
**Pull request by bertfrees**
see https://github.com/daisy/ebraille/issues/289

[Preview](https://raw.githack.com/daisy/ebraille/braille-code-registry-candidates/registries/codes/index.html)

### CODE REVIEW

**Comment by bertfrees** [comment]
That's OK, we can cherry-pick my commits that are still relevant after your commit.

**Comment by mattgarrish** [comment]
Okay, I'll commit the other and let you mod this one.

**Review by mattgarrish — APPROVED** [review]
Having the code first makes more sense for a registry.

**Comment by bertfrees** [comment]
Rebased

**Review by clapierre — APPROVED** [review]

**Pull request merged**
